### ISSUE TITLE
Avoid logout prompt

### ISSUE THREAD

**Issue by fottsia** [epoptes/epoptes#103]
If the teacher launches firefox via Epoptes > Exec command,
and then calls logout,
and firefox has 2 tabs open and prompts to save tabs or not,
which causes a logout delay,
then Ubuntu MATE 18.04 (at least) shows a dialog blaming Epoptes for the delay.

**Comment by frankzimper** [comment]
Can't confirm this on Xfce.

**Comment by alkisg** [comment]
Does XFCE have logout inhibitors?

If you open LibreOffice, type something, and try to logout without saving, does it prevent logout by showing such a dialog?

**Comment by frankzimper** [comment]
No, it just closes the session without asking.

**Comment by alkisg** [comment]
OK then that's why it doesn't happen in XFCE or LXDE.
GNOME, MATE and I think KDE do support logout inhibitors, and epoptes-client doesn't quit on SIGTERM to avoid students trying to bypass it, and now with cgroups the processes ran from the Exec dialog appear to be epoptes-client childs.

I'll try to find a way to mark them childs of the desktop environment or of init, instead of epoptes-client.

**Comment by alkisg** [comment]
It appears that at least GNOME and MATE set DESKTOP_AUTOSTART_ID when launching /etc/xdg/autostart applications. This was inherited by child processes of epoptes-client, and the GNOME/MATE logout prompt then always pointed at epoptes-client instead of the actual application that inhibited logout.

Unsetting DESKTOP_AUTOSTART_ID should solve the issue, please test and comment if that's not the case.
