### ISSUE TITLE
Send files to the clients Desktop

### ISSUE THREAD

**Issue by ftsamis** [Epoptes/epoptes#13]
The students of primary education have difficulties using the Public folder. In some cases it would be more suitable for the teacher to send a file e.g. on the clients desktop, similar to executing a command like

sudo cp file.odt /home/userXX/Desktop/ && chown userXX:userXX /home/userXX/Desktop/file.odt

Launchpad Details: [#LP1356974](https://bugs.launchpad.net/bugs/1356974) Ioannis Kyriazis - 2014-08-14 16:35:30 +0000

**Comment by alkisg** [comment]
The `cp; chown` solution would only work for LTSP installations, while for non-LTSP installations the SSL channel would need to be used. Since we won't support multiple channels in our client <=> server connections, the client would end up getting disconnected from Epoptes while transferring files.

So it's very hard to implement this with the current Epoptes networking design; closing for now.
