### ISSUE TITLE
epoptes.desktop is missing the Comment translations

### ISSUE THREAD

**Issue by freddii** [epoptes/epoptes#131]
based on #129 
epoptes.desktop is missing the translations for Comments ( https://github.com/epoptes/epoptes/blob/master/data/epoptes.desktop.in )

**Comment by alkisg** [comment]
Thanks, fix committed in 7ad711a.
But unfortunately you won't see it immediately; launchpad will need to re-activate the Comment translation (hopefully it has kept all the old translations around), then some days later we would need to re-import the .po into the github sources.

Since it's a small thing, it doesn't deserve its own release, so I'll do it when a new release is planned.

**Comment by alkisg** [comment]
Fortunately the existing translations weren't lost. I just imported them from launchpad, they'll be there in the next release:

[Example de.po translation](https://github.com/epoptes/epoptes/commit/ce934e5ac94c596d2a14a20478482dba726b7205#diff-6686c8173bf4fa70e9c9755259206f2c5c4fa9fde6269d36e5262dcc09abcf25R22)
