### ISSUE TITLE
broadcast full screen does not work

### ISSUE THREAD

**Issue by nektarios1201** [Epoptes/epoptes#72]
epoptes 0.5.10 greek translation
ubuntu mate 18.04 

Broadcast screen in a window works but broadcast in full screen does nothing at all

Thanks 
Nektarios

**Comment by alkisg** [comment]
Hi, epoptes 0.5.10 isn't really supported anymore due to it using Python2/Gtk2, while the new epoptes 1.0.0 has been rewritten to use Python3/Gtk3.

Please add https://launchpad.net/~ts.sch.gr/+archive/ubuntu/ppa to your sources, install epoptes 1.0.0, and test if the problem happens there or not (I believe not, since it's already used in hundreds of schools).

**Comment by gepanos** [comment]
Hi Alkis

I am facing the same problem in my highschool's new lab which has just been delivered a few days ago.
The version of epoptes is the most recent and everything else works fine.
Any suggestions?

(UBUNTU 18.04.3 LTS (Bionic Beaver) 64-bit)

Thanks
George

**Comment by alkisg** [comment]
George if you want you may come to [IRC](ts.sch.gr/repo/irc) for live troubleshooting.

One reason could be if you're running GNOME on Wayland, which doesn't support VNC.
