### ISSUE TITLE
Lost connection when running Epoptes as a remoteapp

### ISSUE THREAD

**Issue by fottsia** [Epoptes/epoptes#89]
If I run Epoptes [as a remoteapp from an LTSP fat client](http://www.epoptes.org/documentation/fat-clients), and a client gets disconnected for any reason (e.g. if I invoke  _Session → Shutdown_), the following message is displayed, and Epoptes is terminated:

> Lost connection with the epoptes service.
> Make sure the service is running and then restart epoptes.

**Comment by alkisg** [comment]
This is actually two different issues:
1. LTSP remoteapps don't launch dbus by default. That means that any dbus calls will fail, which in turn means that there won't be any notification daemon running, and this then causes the exception that terminates Epoptes. But not all applications need dbus; so this issue was fixed by just adding `dbus-launch` to the respective [Epoptes documentation page](http://www.epoptes.org/documentation/fat-clients).
2. And finally, Epoptes should cope with no notification-daemon running anyway. This issue was fixed in https://github.com/Epoptes/epoptes/commit/9594ad1656bd791274afb3b1d965bd627d4d96a7.
